---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest

matrix:
  allow_failures: # Set up allowed failured die to TravisCI swap limitation
    - env: ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - printf "[defaults]\nroles_path = ../" > ansible.cfg

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo

  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)